---
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MY_PROJECT_ID: "45741845"
  GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/execution_environment.git"
  
  DOCKER_IMAGE_BUILD_TARGET_PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
  DOCKER_IMAGE_PUBLISH_NAME: 'ansible-ee'
  DOCKER_IMAGE_PUBLISH_REGISTRY: docker.io/nofusscomputing
  DOCKER_IMAGE_PUBLISH_URL: https://hub.docker.com/r/nofusscomputing/$DOCKER_IMAGE_PUBLISH_NAME



include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: restructure
    file:
      - .gitlab-ci_common.yaml
      - type/docker-image.gitlab-ci.yaml
  #- template: Jobs/Container-Scanning.gitlab-ci.yml # see https://gitlab.com/gitlab-org/gitlab/-/issues/381665



Build/Cache Python Packages:
  stage: build
  image: nofusscomputing/docker-buildx-qemu:dev
  services:
    - name: docker:23-dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker info
    #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - pip3 install setuptools wheel
    - pip3 install commitizen==2.21.0 # version specified so current build works.
    - pip3 install gitlab-ci/gitlab_release/python-module/cz_nfc/.
    - update-binfmts --enable # Important: Ensures execution of other binary formats is enabled in the kernel
    - docker buildx create --driver=docker-container --driver-opt image=moby/buildkit:v0.11.6 --use
    - docker buildx inspect --bootstrap
  script: |
      docker buildx build \
        --file dockerfile-build_cache \
        --platform=$DOCKER_IMAGE_BUILD_TARGET_PLATFORMS . \
        --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN \
        --build-arg CI_API_V4_URL=$CI_API_V4_URL \
        --build-arg CI_PROJECT_ID=$CI_PROJECT_ID
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_COMMIT_BRANCH != "master"'
      allow_failure: true
      when: manual
    - when: never
