INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Ansible-EE
repo_url: https://gitlab.com/nofusscomputing/projects/ansible/execution_environment
edit_uri: '/-/ide/project/nofusscomputing/projects/ansible/execution_environment/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Ansible:

    - projects/ansible/index.md

    - Execution Environment:

      - projects/ansible/execution_environment/index.md

    - Playbooks: projects/ansible/playbooks/index.md

    - Roles: projects/ansible/roles/index.md


- Operations: 

  - operations/index.md

- Contact Us: contact.md

